version: '3.3'

services:
  postgres:
    container_name: postgresdb
    image: postgres:13
    environment:
      - POSTGRES_DB=my_store
      - POSTGRES_USER=userpruebas
      - POSTGRES_PASSWORD=admin123
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  postgres-e2e:
    container_name: postgresdb_e2e
    image: postgres:13
    environment:
      - POSTGRES_DB=db_e2e
      - POSTGRES_USER=e2e
      - POSTGRES_PASSWORD=e2e123
    ports:
      - 5433:5432

  pgadmin:
    container_name: pgadmindb
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80
